/* ============================================================
   example-genomes.js — Local Mock Sequence Database
   ============================================================ */
   
(function () {
  'use strict';

  // These are roughly representative sample sequences, truncated or mocked
  // for the purpose of a fast, local browser-based sequence search tool.
  
  window.EXAMPLE_GENOMES = [
    {
      id: "ECO_LACZ_001",
      organism: "Escherichia coli",
      gene: "lacZ",
      description: "beta-galactosidase",
      type: "DNA",
      sequence: "ATGACCATGATTACGGATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACTTAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGCTTTGCCTGGTTTCCGGCACCAGAAGCGGTGCCGGAAAGCTGGCTGGAGTGCGATCTTCCTGAGGCCGATACTGTCGTCGTCCCCTCAAACTGGCAGATGCACGGTTACGATGCGCCCATCTACACCAACGTAACCTATCCCATTACGGTCAATCCGCCGTTTGTTCCCACGGAGAATCCGACGGGTTGTTACTCGCTCACATTTAATGTTGATGAAAGCTGGCTACAGGAAGGCCAGACGCGAATTATTTTTGATGGCGTTAACTCGGCGTTTCATCTGTGGTGCAACGGGCGCTGGGTCGGTTACGGCCAGGACAGTCGTTTGCCGTCTGAATTTGACCTGAGCGCATTTTTACGCGCCGGAGAAAACCGCCTCGCGGTGATGGTGCTGCGTTGGAGTGACGGCAGTTATCTGGAAGATCAGGATATGTGGCGGATGAGCGGCATTTTCCGTGACGTCTCGTTGCTGCATAAACCGACTACACAAATCAGCGATTTCCATGTTGCCACTCGCTTTAATGATGATTTCAGCCGCGCTGTACTGGAGGCTGAAGTTCAGATGTGCGGCGAGTTGCGTGACTACCTACGGGTAACAGTTTCTTTATGGCAGGGTGAAACGCAGGTCGCCAGCGGCACCGCGCCTTTCGGCGGTGAAATTATCGATGAGCGTGGTGGTTATGCCGATCGCGTCACACTACGTCTGAAC"
    },
    {
      id: "ECO_AMPC_002",
      organism: "Escherichia coli",
      gene: "ampC",
      description: "beta-lactamase",
      type: "DNA",
      sequence: "ATGTTCAAAACGACGCTCTGCGCCTTATTAATTACCGCCTCTTGCTCCACATTTGCTGCTCCTGCTCAAAACAAAAAAAAAAGACTGAGCCAATCAGGTGATGACAGCCACTCCCCCATAAAAAAGACGCAGTAACCAATCGGGTCGCCAGGGCAGGTATTGCCGTTATCGCTGGTAATGCATGGGACGAAAAAGCACCCCAGACCACCGACTGGGTTACGCTGAACCAGAATGGTCTCAACCCCAATAACTTCACTGCTGATGGTTCAGCTGGCGTTGGAAAAACAACCGATGCTGTCGCGCTGCAACCCCTTTACCCTGGGCTTTATCGCGAATAATCAACGCAAATTGCACTGCTACGTGCGTAAACCTCGCCCCCAGCTAAGCCTTGATGAGCGCGCAGACAATTTCCAACAACGCTAAAAGGCCTTCTGCGACAATAAAACGCGCTAACGCAGGCGTCGTCTTCATAACGCTACGCGCTCACAACGTATTTAAACAAATTCAGCGCGATATCCGTAACGTGTTTGAACGGCTGCAACGAGAAAACGTAACACTTCGCGTTATGCTGGACGTCGTACTGAGCAAGCGACGCTTTAATTGCCGGACAAACGCCGAACGCTTCAGAACCAGCGGCTTGCGCGCGCCGTAACCCGCGCAAGAACAGCCGA"    
    },
    {
      id: "HOM_MTCO1_001",
      organism: "Homo sapiens",
      gene: "MT-CO1",
      description: "cytochrome c oxidase subunit I (mitochondrion)",
      type: "DNA",
      sequence: "ATGTTCGCCGACCGTTGACTATTCTCTACAAACCACAAAGACATTGGAACACTATACCTATTATTCGGCGCATGAGCTGGAGTCCTAGGCACAGCTCTAAGCCTCCTTATTCGAGCCGAGCTGGGCCAGCCAGGCAACCTTCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCCCATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGGCTTTGGCAACTGACTAGTTCCCCTGATAATCGGTGCCCCCGATATGGCGTTTCCCCGCATAAACAACATAAGCTTCTGACTCTTACCTCCCTCTCTCCTACTCCTGCTCGCATCTGCTATAGTGGAGGCCGGAGCAGGAACAGGTTGAACAGTCTACCCTCCCTTAGCAGGGAACTACTCCCACCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTACACCTAGCAGGTGTCTCCTCTATCTTAGGGGCCATCAATTTCATCACAACAATTATCAATATAAAACCCCCTGCCATAACCCAATACCAAACGCCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCCTACTTCTCCTATCTCTCCCAGTCCTAGCTGCTGGCATCACTATACTACTAACAGACCGCAACCTCAACACCACCTTCTTCGACCCCGCCGGAGGAGGAGACCCCATTCTATACCAACACCTATTCTGATTTTTCGGTCACCCTGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATCTCCCATATTGTAACTTACTACTCCGGAAAAAAAGAACCATTTGGATACATAGGTATGGTCTGAGCTATGATATCAATTGGCTTCCTAGGGTTTATCGTGT"
    },
    {
      id: "HOM_TP53_002",
      organism: "Homo sapiens",
      gene: "TP53",
      description: "tumor protein p53",
      type: "DNA",
      sequence: "ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCGACATAGTGTGGTGGTGCCCTATGAGCCGCCTGAGGTTGGCTCTGACTGTACCACCATCCACTACAACTACATGTGTAACAGTTCCTGCATGGGCGGCATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCAGTGGTAATCTACTGGGACGGAACAGCTTTGAGGTGCGTGTTTGTGCCTGTCCTGGGAGAGACCGGCGCACAGAGGAAGAGAATCTCCGCAAGAAAGGGGAGCCTCACCACGAGCTGCCCCCAGGGAGCACTAAGCGAGCACTGCCCAACAACACCAGCTCCTCTCCCCAGCCAAAGAAGAAACCACTGGATGGAGAATATTTCACCCTTCAGATCCGTGGGCGTGAGCGCTTCGAGATGTTCCGAGAGCTGAATGAGGCCTTGGAACTCAAGGATGCCCAGGCTGGGAAGGAGCCAGGGGGGAGCAGGGCTCACTCCAGCCACCTGAAGTCCAAAAAGGGTCAGTCTACCTCCCGCCATAAAAAACTCATGTTCAAGACAGAAGGGCCTGACTCAGACTGA"
    },
    {
      id: "ARA_CAB1_001",
      organism: "Arabidopsis thaliana",
      gene: "CAB1",
      description: "chlorophyll a/b binding protein 1",
      type: "DNA",
      sequence: "ATGGCCTCATCAGCTGTAACAACCTACAAATCTTCCTCTGCTCCTTCACCCATGTCTTCTTCTCTCCCATCACAACAAAACAAAACACAACACAAATCAACTTCAAGATCAACTTCTCTCCAAAACCCTAAACCAACTTCTTTCCCAAAGCCAAAGCTTAACGTTAGATGGGGTTCAGTCAAAGCTGGAAGAAACTACTTTGATGATGGTGATAACCCATTAGATCATTCCCCACAACCTAGAGGCGAAGCCACAGATCCAGAGATCCCAGAGAAAGGTCTAATAAGTCAACCATGGCTTCAACCACTCTTAGAAACAGCTAACGGTATCTTCATCTTGATGGTAACTTTCCCTGTTTCTTACACAGCTAGATTCACAGCTGAGCCTAACAACAAGGCACCGTACATTGCTGACCACAAGATTGGAACTGATGTAGTTTACAATGGATACAGAGATTGGGAACCACGTCGAATCGCAGAAGGTCTTGTTAAGAACCCTAATGTGTCTGCCTTCAACGTTTCAATCTTCGTAATCTTCTTAATCTTAGCCGTTGCCTTCGCATCAACACTTCTCGAGAATGCTGCATTGGGTTCAGAACGTCTTCATATCTACTGGATTGCTGCTAACCCTGTTAAGTCTGCACCAGACAACATCTCTCTCTCTTTGGGTGCTAATCCCACCGGTACTGTGATCTTCTTCTCCGGACTCTCATTCTCTGCTGGTTCTACCGTAAATCTCTCCTACAAGGTTACCGAGATGGCTCACGCTCACGGTCTCCTCTACTCTACCGATTTGGACGTTTACATGCCAGGACCAACTGTAAACGTTAAAGAAGGAAACGGTGATAACCACCCATTCCCATTAGTTACTGACGCTAAACCACAA"
    },
    {
      id: "ARA_FT_002",
      organism: "Arabidopsis thaliana",
      gene: "FT",
      description: "FLOWERING LOCUS T",
      type: "DNA",
      sequence: "ATGTCTATAAATATAAGAGACCCTCTTATAGTAAGCAGAGTTGTTGGAGACGTTCTTGATCCGTTTAATAGATCAATCACTCTAAAGGTTACTTATGGCCAAAGAGAGGTTACTAATGGCTTGGATCTTAGGCCTTCGCAAGTTCAAAACAAGCCAAGAATAGAAGTTCCTGAAATTGATGGTCAAGGATCTGAGAACGAGGTAATACCTGTTCGAGTCTTTCACCACGGATCATACTCAAAAACCCTAACCATTGAACCACCACAAGACATTACAAGAAACTGGGCTGAGAATGATCTAGCGAATTTCACGAGAAAATCTGTGGATCATACTGATCCAATGTCAATTCTAGTGAATTACAATGGAAGGAACCTATTCATACTAGAAGACGTAAATAAGCAAGAATATGACAAGCCTTCTCAGTATTATCCGAGTTTGGACCAAGGATTGTACGAACTTATTGGGGTATATATGCATTACACTCTTCCTCTTATTGGAAACCTCTAG"
    }
  ];

})();
